# Generated by Django 5.2.6 on 2025-09-22 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobEntryFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="job_entry/files/", verbose_name="File"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="api.jobentry",
                        verbose_name="Job entry",
                    ),
                ),
            ],
        ),
    ]
