# Generated by Django 5.2.7 on 2025-11-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobentry',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
