# Generated by Django 5.2.6 on 2025-09-28 14:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_jobentryfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestToAdd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_sent",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Request sent at",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_requests",
                        to="api.handyman",
                        verbose_name="Requested by",
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="jobentryfile",
            options={
                "ordering": ["uploaded_at"],
                "verbose_name": "Job entry file",
                "verbose_name_plural": "Job entry files",
            },
        ),
        migrations.CreateModel(
            name="RequestToAddCategory",
            fields=[
                (
                    "requesttoadd_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.requesttoadd",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Category title"),
                ),
            ],
            options={
                "verbose_name": "Request to add category",
                "verbose_name_plural": "Requests to add category",
                "ordering": ["request_sent"],
            },
            bases=("api.requesttoadd",),
        ),
        migrations.CreateModel(
            name="RequestToAddService",
            fields=[
                (
                    "requesttoadd_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.requesttoadd",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Service title"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.category",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Request to add service",
                "verbose_name_plural": "Requests to add service",
                "ordering": ["request_sent"],
            },
            bases=("api.requesttoadd",),
        ),
    ]
