# Generated by Django 5.2.7 on 2025-12-01 20:48

from django.db import migrations, models
from django.db.migrations import RunPython


def setDecisionField(apps, schema_editor):
    RequestToAdd = apps.get_model('api', 'RequestToAdd')
    for request in RequestToAdd.objects.all():
        request.decision = 2 if request.is_rejected else 1
        request.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_jobentry_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttoadd',
            name='decision',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected')], default=0, verbose_name='Decision state'),
        ),
        RunPython(setDecisionField),
    ]
