# Generated by Django 5.2.7 on 2025-12-01 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_requesttoadd_decision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesttoadd',
            name='is_rejected',
        ),
    ]
