# Generated by Django 5.2.6 on 2025-09-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_requesttoadd_alter_jobentryfile_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="requesttoadd",
            name="is_rejected",
            field=models.BooleanField(default=False, verbose_name="Is accepted"),
        ),
    ]
